### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by apoorvajhanwer** [WCoetser/RandomUsefulCode#1]
I found your code very useful.Just a suggestion for making it better.
For TriangleStripVertexBuffer and TriangleVertexBuffer Class which inherit VertexBuffer class
use
UnItialized instances of base class like
TriangleStripVertexBuffer.prototype = Object.create(VertexBuffer.prototype);
instead of
TriangleStripVertexBuffer.prototype = new VertexBuffer();
You can find the javascript documentation here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create

**Comment by apoorvajhanwer** [comment]
The code wasn't working  correctly on Internet Explorer. The issue was with the mouse coordinates in float so for mapping the coordinates to array index you need to convert it  explicitly into Integer
using parseInt 

Viewport.prototype.GetColourMapColour = function (x, y) {
    var firstAddress = (this.viewportHeight - 1 - parseInt(y)) \* this.viewportWidth \* 4 + parseInt(x) \* 4;
}

**Comment by WCoetser** [comment]
Thanks - I changed it to Object.create after reading http://stackoverflow.com/questions/4166616/understanding-the-difference-between-object-create-and-new-somefunction. I could not find any problems in IE though - I tested with IE 11. (I.e. I could still pick the triangle and square). Could you remember the exact steps in order to reproduce the problem?
